services:
  db:
    image: postgres:16.2-bookworm
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "todoapp1234"
      POSTGRES_USER: "todoapp"
      POSTGRES_DB: "todoapp"
    volumes:
      - db:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
  app:
    build: .
    ports:
      - 8000:8000
volumes:
  db: {}
